# Generated by Django 4.2.7 on 2026-02-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_2d2a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_views_c_5941c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_created_eee82f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_categor_5a4a66_idx',
        ),
    ]
