# Generated by Django 4.2.7 on 2026-02-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_catalog_pro_price_2d2a4c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
    ]
